name: Vercel Deploy

on:
  push:
    branches:
      - main
  # eslint-disable-next-line yml/no-empty-mapping-value
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Check Branch
        id: branch
        if: ${{ github.ref  == 'refs/heads/main' }}
        run: |
          echo "args=--prod" >> $GITHUB_OUTPUT
          echo "comment=false" >> $GITHUB_OUTPUT

      - name: Deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-args: ${{ steps.branch.outputs.args }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: ${{ steps.branch.outputs.comment != 'false' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
